# Generated by Django 5.1.5 on 2025-01-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GodownList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('godown_name', models.CharField(blank=True, max_length=255, null=True)),
                ('godown_address', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
