# Generated by Django 5.1.5 on 2025-01-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_godownlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='parent',
        ),
    ]
