# Generated by Django 5.1.5 on 2025-01-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_division_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.TextField()),
            ],
        ),
    ]
