# Generated by Django 5.1.5 on 2025-01-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shopbankinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=255, verbose_name='পেমেন্ট মেথড')),
            ],
        ),
    ]
