# Generated by Django 5.1.5 on 2025-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_employee_education_bankingdetails_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('Shop Admin', 'Shop Admin'), ('Manager', 'Manager'), ('Account Officer', 'Account Officer'), ('Collection Representative (CR)', 'Collection Representative (CR)'), ('Sales Representative (SR)', 'Sales Representative (SR)')], max_length=50),
        ),
    ]
