# Generated by Django 5.1.5 on 2025-02-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_employee_blood_group_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingdetails',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankingdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankingdetails',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
