# Generated by Django 5.1.5 on 2025-02-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0007_employee_education_bankingdetails_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mohajon',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('business_type', models.CharField(choices=[('মহাজন', 'মহাজন'), ('চাষী', 'চাষী')], max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=50, null=True)),
                ('market_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_number_1', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('present_division', models.CharField(blank=True, max_length=255, null=True)),
                ('present_district', models.CharField(blank=True, max_length=255, null=True)),
                ('present_thana', models.CharField(blank=True, max_length=255, null=True)),
                ('present_route', models.CharField(blank=True, max_length=255, null=True)),
                ('present_area', models.CharField(blank=True, max_length=255, null=True)),
                ('present_village_street', models.CharField(blank=True, max_length=255, null=True)),
                ('present_post_office', models.CharField(blank=True, max_length=255, null=True)),
                ('present_post_code', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_division', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_thana', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_route', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_area', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_village_street', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_post_office', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_post_code', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('shop_photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('nid_front_photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('nid_back_photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('previous_account', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('khatian_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shopbankinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_details', to='person.mohajon')),
            ],
        ),
    ]
