# Generated by Django 5.1.5 on 2025-02-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mohajon',
            name='business_type',
            field=models.CharField(choices=[('মহাজন', 'মহাজন'), ('বেপারী/চাষী', 'বেপারী/চাষী')], max_length=255),
        ),
    ]
